= XYZ Reader

This is a redesign of the XYZ Reader project in Udacity's Android Nanodegree app to follow the Material Design guidelines and translate a set of static design mocks to a living and breathing app.

In this app :
App uses the Design Support library and its provided widget types (FloatingActionButton, AppBarLayout, SnackBar, etc).

App uses CoordinatorLayout for the main Activity.

App theme extends from AppCompat.

App uses an AppBar and associated Toolbars.

App provides a Floating Action Button for the most common action(s).

App properly specifies elevations for app bars, FABs, and other elements specified in the Material Design specification.

App has a consistent color theme defined in styles.xml. Color theme does not impact usability of the app.

App provides sufficient space between text and surrounding elements.

App uses images that are high quality, specific, and full bleed.

App uses fonts that are either the Android defaults, are complementary, and aren't otherwise distracting.
